version: '3.5'

services:
    minio:
        container_name: minio-s3-storage
        image: "minio/minio"
        ports:
            - "9000:9000"
        env_file:
            - docker-compose.env
        command: server /data
        networks:
            - network

    postgres:
        container_name: postgres-database
        image: postgres:10.5
        restart: always
        env_file:
            - docker-compose.env
        logging:
            options:
                max-size: 10m
                max-file: "3"
        ports:
            - '5432:5432'
        networks:
            - network

    broker:
        container_name: message-broker
        image: rabbitmq:3.8.2-management-alpine
        env_file:
            - docker-compose.env
        ports:
            - "15672:15672"
            - "5672:5672"
        networks:
            - network

    audio:
        build: ./src/workers
        container_name: audio-workers
        env_file:
            - docker-compose.env
        links:
            - broker:broker
            - minio:minio
        volumes:
            - ${PWD}/src/workers/:/workers
            - ${PWD}/src/common:/workers/common
        networks:
            - network
        # command: celery -A audio.tasks worker --loglevel=INFO
        # For development
        command: watchmedo auto-restart --directory=audio --pattern=tasks.py --recursive -- celery -A audio.tasks worker --loglevel=INFO

    api:
        build: ./src/api
        container_name: api
        env_file:
            - docker-compose.env
        links:
            - broker:broker
            - minio:minio
        ports:
            - "5000:5000"
        networks:
            - network
        volumes:
            - ${PWD}/src/api:/api
            - ${PWD}/src/common:/api/common

    client:
        build: ./src/client
        container_name: client
        environment:
            - NODE_ENV=development
        links:
            - api:api
        ports:
            - "3000:3000"
        networks:
            - network
        # Uncomment for front end dev work
        # volumes:
        #     - ${PWD}/src/client:/app

networks:
    network: {}
